/var/lib/private/ is mostly used by dynamic users e.g. managed by systemd like
the default in kanidm's systemd service.

However we don't use dynamic users and create a system user on installation.
So we can keep /var/lib/.
---
--- a/examples/server.toml
+++ b/examples/server.toml
@@ -21,7 +21,7 @@ bindaddress = "[::]:443"
 # trust_x_forward_for = false
 #
 #   The path to the kanidm database.
-db_path = "/var/lib/private/kanidm/kanidm.db"
+db_path = "/var/lib/kanidm/kanidm.db"
 #
 #   If you have a known filesystem, kanidm can tune the
 #   database page size to match. Valid choices are:
@@ -47,8 +47,8 @@ db_path = "/var/lib/private/kanidm/kanidm.db"
 #   TLS chain and key in pem format. Both must be present.
 #   If the server receives a SIGHUP, these files will be
 #   re-read and reloaded if their content is valid.
-tls_chain = "/var/lib/private/kanidm/chain.pem"
-tls_key = "/var/lib/private/kanidm/key.pem"
+tls_chain = "/var/lib/kanidm/chain.pem"
+tls_key = "/var/lib/kanidm/key.pem"
 #
 #   The log level of the server. May be one of info, debug, trace
 #
@@ -85,7 +85,7 @@ origin = "https://idm.example.com:8443"
 #
 [online_backup]
 #   The path to the output folder for online backups
-path = "/var/lib/private/kanidm/backups/"
+path = "/var/lib/kanidm/backups/"
 #   The schedule to run online backups (see https://crontab.guru/)
 #   every day at 22:00 UTC (default)
 schedule = "00 22 * * *"
