# cloudflared's configuration file
# cloudflare tunnel see: 
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/#4-create-a-configuration-file
