global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'
  traefik:
    address: 'localhost:8080'

api:
  insecure: true
  dashboard: true

ping: {}

#certificatesResolvers:
#  sample:
#    acme:
#      email: ''
#      storage: traefik/acme/account
#      dnsChallenge:
#        provider: cloudflare
#        delayBeforeCheck: 10
