global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  filePath: /var/log/traefik/traefik.log
  compress: 3
accessLog:
  filePath: /var/log/traefik/access.log
  compress: 3

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'
  traefik:
    address: 'localhost:8080'
api:
  insecure: true
  dashboard: true

pilot:
  dashboard: false

ping: {}

#certificatesResolvers:
#  sample:
#    acme:
#      email: ''
#      storage: traefik/acme/account
#      dnsChallenge:
#        provider: cloudflare
#        delayBeforeCheck: 10
